version: "3.3"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: unless-stopped
    expose:
      - 8000
      - 9000
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/portainer:/data
  jenkins:
    image: jenkins/jenkins:latest 
    container_name: jenkins
    restart: unless-stopped
    expose:
      - 8080
      - 50000
    networks:
      - proxy
    volumes:
      - ./data/jenkins:/var/jenkins_home
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    restart: unless-stopped
    networks:
      - proxy
    ports: 
     - 80:80
     - 443:443
    depends_on:
     - jenkins
     - portainer
networks:
  proxy:
