server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name _;
	
    	return 301 https://$server_name$request_uri;
}

server {
	listen 443 ssl default_server;
	listen [::]:443 default_server;

	root   /usr/share/nginx/html;
	index  index.html index.htm;

	server_name _;
	
	include snippets/ssl-params.conf;
        include snippets/self-signed.conf;

	location / {
		try_files $uri $uri/ =404;
	}
}
